Remove imported assets during tests and fix Lookup tests
IMQS/Core pull request #23
Opened 2021-03-24 11:44 UTC by CalebBredekamp

The Import tests were the issue for `AssetControllerQueryAPITest.queryByTags` since the import dataset now includes tags. So I've just added a section to delete the imported assets.

The Lookup tests on the other hand were expecting a description which is null. But it looks like if a description is null in the DB, its ignored during the return, hence the tests failing. Assuming this is desired behaviour I've just removed the expectation from the test where the description is null.

2021-03-24 11:52 UTC, frankvanrietimqs commented on Service/src/test/java/za/co/imqs/api/TestImport.java
> +        UUID[] assets = {
This is terribly fragile as it depends on the contents of the file. I would suggest that you make use of the AssetTestingController delete endpoint to remove uuids that you have gotten by querying the database for the available uuids or perhaps cleaner add an endpoint that will do a blanket delete

2021-03-24 11:53 UTC, frankvanrietimqs requested changes
Please see comment

2021-03-25 14:09 UTC, frankvanrietimqs commented on Service/src/main/java/za/co/imqs/coreservice/controller/AssetTestingController.java
> +        final List<UUID> uuids =
This is test code so everything does not have to bwe super correct, but lets use this as a learning opportunity.

I suggest you move getting the list of uuids into the repository layer. The layering s all about encapsulation and abstraction.  By having the query here knowledge about what the database internals look like are escaping the repository layer.

2021-03-25 14:31 UTC, CalebBredekamp commented on Service/src/main/java/za/co/imqs/coreservice/controller/AssetTestingController.java
> +        final List<UUID> uuids =
Alrighty, will do

2021-03-26 08:36 UTC, frankvanrietimqs commented on Service/src/main/java/za/co/imqs/coreservice/controller/AssetTestingController.java
> +        final List<UUID> uuids = assetReader.getAllAssets();
Closer :) 
Consider that you are not being picky on what you are deleting. Would it not be much simpler to add a deleteAll method to CoreAssetWriter?

2021-03-26 16:12 UTC, frankvanrietimqs approved these changes

2021-03-29 06:23 UTC, merged