Add ref_quantity_types
IMQS/Core pull request #36
Opened 2021-04-19 16:10 UTC by CalebBredekamp

This is a bit of a long one, although most of the additions are changelog edits. Only the schema changes have been added in this PR.

2021-04-19 16:28 UTC, frankvanrietimqs approved these changes
I did not look at all of the nitty gritty of the sql scripts. The real test is to see if an upgrade from the dtpw-prod branch is successfull. ask me for a db backup tomorrow.

2021-04-19 16:28 UTC, frankvanrietimqs commented on Service/src/main/resources/public/quantity_types_master_data.sql
> +INSERT INTO public.ref_quantity_types (k,v) VALUES ('1', 'extent') ON CONFLICT (k) DO NOTHING;
You'll see that we never use a number. We could, but it is not terribly obvious what '1' means when you encounter it.  Try a code that suggets what it is. Maybe even `EXTENT`

2021-04-19 16:30 UTC, CalebBredekamp commented on Service/src/main/resources/1_changelog_public.json
> +          "onFail": "CONTINUE",
The 'continues' change later to 'mark_ran'

2021-04-19 16:30 UTC, CalebBredekamp commented on Service/src/main/resources/1_changelog_public.json
> +            "sql": "SELECT COUNT(indexname) FROM pg_catalog.pg_indexes WHERE indexname='ref_quantity_types_k_idx'"
I had to use pg_catalog here because information_schema doesn't have an index table to check

2021-04-19 16:30 UTC, CalebBredekamp commented on Service/src/main/resources/1_changelog_public.json
> +            "expectedResult": 0,
See above comment on pg_catalog

2021-04-19 16:30 UTC, CalebBredekamp commented on Service/src/main/resources/public/quantity_types_master_data.sql
> +INSERT INTO public.ref_quantity_types (k,v) VALUES ('1', 'extent') ON CONFLICT (k) DO NOTHING;
Since we only have the one type at the moment, this is more necessary in the manual scripts

2021-04-19 16:30 UTC, CalebBredekamp commented on Service/manual/06_quantity_types.sql
> +DO
If there is existing data in `quantity` this will loop through and change `code` to the correct key value according to the master data in ref_quantity_types

2021-04-19 16:30 UTC, CalebBredekamp commented on Service/manual/07_lastchanged.sql
> +                   'trig_fn_on_update_ref_table(''%s\\'');', trig_new_convention, table_qualifier, table_qualifier);
The double backslash gets removed

2021-04-19 16:30 UTC, CalebBredekamp commented on Service/manual/07_lastchanged.sql
> +
Since tags and ref_facility_type match the changlelogs, they are set manually here.

2021-04-21 13:03 UTC, frankvanrietimqs approved these changes

2021-04-29 09:35 UTC, frankvanrietimqs requested changes
Happy with the changes, please just update the API documentation accordingly

2021-04-30 12:15 UTC, frankvanrietimqs approved these changes
Good!

2021-04-30 13:06 UTC, merged