Dup assets check
IMQS/Core pull request #4
Opened 2021-02-12 13:27 UTC by CalebBredekamp

Hi Frank,

Let me know if you want me to change anything. Also, the exported zip file still uses the name strategy that performing the Core Export used. Let me know if that shouldn't be the case

2021-02-15 07:02 UTC, frankvanrietimqs requested changes

2021-02-15 07:02 UTC, frankvanrietimqs commented on Service/src/main/java/za/co/imqs/coreservice/controller/ExportController.java
> +            method = RequestMethod.GET, value = "/exporter/duplicate-check"
The name  is not specific enough see comment about labels below

2021-02-15 07:02 UTC, frankvanrietimqs commented on Service/src/main/java/za/co/imqs/coreservice/controller/ExportController.java
> +        System.out.println("\n\nWe're in exportDuplicateAssets\n\n");
Using system.out is a big no no in production. It won't end up in log files

2021-02-15 07:15 UTC, frankvanrietimqs requested changes

2021-02-15 07:15 UTC, frankvanrietimqs commented on Service/src/main/java/za/co/imqs/coreservice/controller/ExportController.java
> +        final String query = DtpwReport.DUPLICATE_ASSET_QUERY;
Why the extra variables when the values can be used directly as parameters (with no loss of clarity)

2021-02-15 07:15 UTC, frankvanrietimqs commented on Service/src/main/java/za/co/imqs/coreservice/reports/DtpwReport.java
> +public class DtpwReport {
I see here that you are trying to add some abstraction to how the query strings are managed. You ar ewelcome to disagree with me but what you have done here is to just move the constants to another file. The ExportController is still no less directly coupled to the constants and the constants are all in the same file (as they would have been if they remained in the controller class). Since there is avery direct relationship between the export method and teh query string I would suggets just leaving them as constants in the exporter file until such time as we have enough use cases to decide in what direction to take further abstraction.

2021-02-15 13:56 UTC, CalebBredekamp commented on Service/src/main/java/za/co/imqs/coreservice/reports/DtpwReport.java
> +public class DtpwReport {
I wasn't trying to add abstraction, just trying to give an indication on how I thought the abstraction might work when we have more use cases. I was thinking it might be easier to abstract if it starts in this format from the get go. I can of course move it back to the other class though if you prefer

2021-02-17 12:22 UTC, frankvanrietimqs commented on Service/src/main/java/za/co/imqs/coreservice/controller/ExportController.java
> +        final String allAssetsQuery = "SELECT * FROM dtpw.dtpw_export_view ORDER BY func_loc_path";
The compiler may or may not be clever enough to figure out that this is a constant, but style wise I think it is preferable to declare as static final

2021-02-18 06:20 UTC, frankvanrietimqs approved these changes

2021-02-24 07:17 UTC, CalebBredekamp commented
Merged to master

2021-02-24 07:17 UTC, CalebBredekamp commented
Merged to master

2021-02-24 07:17 UTC, closed without merging