initial test
IMQS/Core pull request #5
Opened 2021-02-15 14:14 UTC by JohnkDevHub

AssetControllerGetAPITest

2021-02-15 14:31 UTC, frankvanrietimqs reviewed
Looks like you get the genarl idea. Maybe do a test where you create or update something next

2021-02-15 14:31 UTC, frankvanrietimqs commented on Service/pom.xml
> +        <dependency>
Why on God's green earth would teh service be dependent on itself?

2021-02-15 14:31 UTC, frankvanrietimqs commented on Service/src/test/java/za/co/imqs/api/asset/AssetControllerGetAPITest.java
> + * User: frankvr
You might want to fix that

2021-02-15 14:31 UTC, frankvanrietimqs commented on Service/src/test/java/za/co/imqs/api/asset/AssetControllerGetAPITest.java
> +                get("/assets/{uuid}",NONEXISTENT_ASSET).
Note we add spaces after the comma

2021-02-15 15:53 UTC, JohnkDevHub commented on Service/src/test/java/za/co/imqs/api/asset/AssetControllerGetAPITest.java
> + * User: frankvr
okay

2021-02-15 15:53 UTC, JohnkDevHub commented on Service/src/test/java/za/co/imqs/api/asset/AssetControllerGetAPITest.java
> +                get("/assets/{uuid}",NONEXISTENT_ASSET).
okay

2021-02-17 13:29 UTC, frankvanrietimqs requested changes

2021-02-17 13:29 UTC, frankvanrietimqs commented on Service/src/test/java/za/co/imqs/api/asset/AssetControllerDeleteLinkAPITest.java
> +        given().
No that I see the names I gave these tests. They are pretty bad names.  `addAssetDeleteLinkSuccess` for instance should be called something like `addAssetLink` or `addLinkToAsse`t. There is no 'delete' here. Please update the names so they make sense.

2021-02-17 13:29 UTC, frankvanrietimqs commented on Service/src/test/java/za/co/imqs/api/asset/AssetControllerDeleteLinkAPITest.java
> +                then().assertThat().statusCode(HttpStatus.SC_NOT_FOUND);
If you check the documentation you will see that 404 is not one of the possible return values. The server does not complain if you ask it to delete something that does not exist. 200 is the expected result.

2021-02-18 13:28 UTC, JohnkDevHub commented on Service/src/test/java/za/co/imqs/api/asset/AssetControllerDeleteLinkAPITest.java
> +        given().
okay

2021-02-18 13:30 UTC, JohnkDevHub commented on Service/src/test/java/za/co/imqs/api/asset/AssetControllerDeleteLinkAPITest.java
> +                then().assertThat().statusCode(HttpStatus.SC_NOT_FOUND);
okay

2021-02-18 13:32 UTC, JohnkDevHub commented
I have read your observations from yesterday commits. changes will be made.

2021-02-18 14:12 UTC, frankvanrietimqs requested changes

2021-02-18 14:12 UTC, frankvanrietimqs commented on Service/src/test/java/za/co/imqs/api/asset/AssetControllerGetByGroupingAPITest.java
> +        given().
This is also a pretty meaningless test. Testing an empty database won't deliver false positives. I suggest  that you call getAssetByGroupingSuccess() to have a system populated with data and then try and get the non-existent asset to make sure

2021-02-18 14:12 UTC, frankvanrietimqs commented on Service/src/test/java/za/co/imqs/api/asset/AssetControllerGetByLinkAPITest.java
> +        // No Asset linked
Again an empty dataset proves nothing

2021-02-18 17:01 UTC, JohnkDevHub commented on Service/src/test/java/za/co/imqs/api/asset/AssetControllerGetByGroupingAPITest.java
> +        int groupedAssetCount=2;
Okay

2021-02-18 17:07 UTC, JohnkDevHub commented on Service/src/test/java/za/co/imqs/api/asset/AssetControllerGetByGroupingAPITest.java
> +        given().
okay

2021-02-19 12:10 UTC, frankvanrietimqs reviewed
Looks good, please proceed with the other tests

2021-02-19 12:10 UTC, frankvanrietimqs commented on Service/src/test/java/za/co/imqs/api/asset/AbstractAssetControllerAPITest.java
> +    public static final UUID THE_FIRTH_ASSET = UUID.fromString("455ac960-8fc6-409f-b2ef-cd5be4ebe687");
FIFTH

2021-02-19 13:19 UTC, JohnkDevHub commented on Service/src/test/java/za/co/imqs/api/asset/AbstractAssetControllerAPITest.java
> +    public static final UUID THE_FIRTH_ASSET = UUID.fromString("455ac960-8fc6-409f-b2ef-cd5be4ebe687");
okay

2021-02-22 13:02 UTC, frankvanrietimqs approved these changes

2021-02-25 11:05 UTC, merged